/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GlossaryTerm = IDL.Record({
  'term' : IDL.Text,
  'example' : IDL.Text,
  'usage' : IDL.Text,
  'definition' : IDL.Text,
});
export const LearningSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatSourceType = IDL.Variant({
  'internetResult' : IDL.Null,
  'article' : IDL.Null,
  'learningSection' : IDL.Null,
  'glossary' : IDL.Null,
});
export const InternetResultSource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'snippet' : IDL.Text,
});
export const ChatAskResponseSource = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'type' : ChatSourceType,
  'internetSource' : IDL.Opt(InternetResultSource),
});
export const ChatAskResponsePayload = IDL.Record({
  'sources' : IDL.Vec(ChatAskResponseSource),
});
export const GlossarySnapshot = IDL.Record({
  'terms' : IDL.Vec(IDL.Tuple(IDL.Text, GlossaryTerm)),
  'termCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'version' : IDL.Nat,
});
export const Feedback = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Nifty50StockData = IDL.Record({
  'ltp' : IDL.Float64,
  'dayClose' : IDL.Float64,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Nat,
  'author' : IDL.Text,
  'lastUpdatedAt' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const GlossaryDiagnostic = IDL.Record({
  'key' : IDL.Text,
  'term' : IDL.Text,
});
export const GlossaryStats = IDL.Record({
  'lastSnapshotVersion' : IDL.Opt(IDL.Nat),
  'currentTermCount' : IDL.Nat,
  'lastBackupTimestamp' : IDL.Opt(IDL.Int),
  'lastRestoreTimestamp' : IDL.Opt(IDL.Int),
});
export const MarketHour = IDL.Record({
  'closeMinute' : IDL.Nat,
  'closeHour' : IDL.Nat,
  'weekday' : IDL.Nat,
  'openMinute' : IDL.Nat,
  'openHour' : IDL.Nat,
});
export const Stock = IDL.Record({
  'ltp' : IDL.Float64,
  'dayClose' : IDL.Float64,
  'companyName' : IDL.Text,
  'symbol' : IDL.Text,
});
export const ResearchPaper = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
});
export const GlossaryBatchTerm = IDL.Record({
  'key' : IDL.Text,
  'term' : GlossaryTerm,
});
export const GlossaryBatch = IDL.Record({
  'terms' : IDL.Vec(GlossaryBatchTerm),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addBlog' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addGlossaryTerm' : IDL.Func([IDL.Text, GlossaryTerm], [], []),
  'addLearningSection' : IDL.Func([IDL.Text, LearningSection], [], []),
  'addResearchPaper' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chatAsk' : IDL.Func([IDL.Text], [ChatAskResponsePayload], ['query']),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [], []),
  'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
  'deleteGlossaryTerm' : IDL.Func([IDL.Text], [], []),
  'deleteLearningSection' : IDL.Func([IDL.Text], [], []),
  'deleteResearchPaper' : IDL.Func([IDL.Nat], [], []),
  'exportGlossarySnapshot' : IDL.Func([], [GlossarySnapshot], []),
  'getAllFeedback' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Feedback))],
      ['query'],
    ),
  'getAllNifty50Data' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Nifty50StockData))],
      ['query'],
    ),
  'getApplicationPaths' : IDL.Func([], [IDL.Text], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticlesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogs' : IDL.Func([IDL.Bool], [IDL.Vec(BlogPost)], ['query']),
  'getBlogsByCategory' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlossaryDiagnosticsByPrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GlossaryDiagnostic)],
      ['query'],
    ),
  'getGlossarySnapshotStats' : IDL.Func([], [GlossaryStats], ['query']),
  'getGlossaryTerms' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, GlossaryTerm))],
      ['query'],
    ),
  'getLearningSection' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LearningSection)],
      ['query'],
    ),
  'getLearningSections' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, LearningSection))],
      ['query'],
    ),
  'getMaintenanceStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getMarketHours' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MarketHour))],
      ['query'],
    ),
  'getMarketStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getNifty50Data' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Nifty50StockData)],
      ['query'],
    ),
  'getNifty50Stocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
  'getNifty50Symbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getResearchPaper' : IDL.Func([IDL.Nat], [IDL.Opt(ResearchPaper)], ['query']),
  'getResearchPapers' : IDL.Func([], [IDL.Vec(ResearchPaper)], ['query']),
  'getStock' : IDL.Func([IDL.Text], [IDL.Opt(Stock)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeMarketHours' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMarketOpen' : IDL.Func([], [IDL.Bool], ['query']),
  'publishGlossaryBatch' : IDL.Func([GlossaryBatch], [], []),
  'replaceGlossaryWithSnapshot' : IDL.Func([GlossarySnapshot], [], []),
  'restoreGlossaryFromSnapshot' : IDL.Func([GlossarySnapshot], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchGlossary' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, GlossaryTerm))],
      ['query'],
    ),
  'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitJobTitle' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArticle' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBlog' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateBlogUpdatedTime' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateGlossaryTerm' : IDL.Func([IDL.Text, GlossaryTerm], [], []),
  'updateLearningSection' : IDL.Func([IDL.Text, LearningSection], [], []),
  'updateNifty50Data' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'updateStock' : IDL.Func([IDL.Text, Stock], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GlossaryTerm = IDL.Record({
    'term' : IDL.Text,
    'example' : IDL.Text,
    'usage' : IDL.Text,
    'definition' : IDL.Text,
  });
  const LearningSection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatSourceType = IDL.Variant({
    'internetResult' : IDL.Null,
    'article' : IDL.Null,
    'learningSection' : IDL.Null,
    'glossary' : IDL.Null,
  });
  const InternetResultSource = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'snippet' : IDL.Text,
  });
  const ChatAskResponseSource = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'type' : ChatSourceType,
    'internetSource' : IDL.Opt(InternetResultSource),
  });
  const ChatAskResponsePayload = IDL.Record({
    'sources' : IDL.Vec(ChatAskResponseSource),
  });
  const GlossarySnapshot = IDL.Record({
    'terms' : IDL.Vec(IDL.Tuple(IDL.Text, GlossaryTerm)),
    'termCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'version' : IDL.Nat,
  });
  const Feedback = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Nifty50StockData = IDL.Record({
    'ltp' : IDL.Float64,
    'dayClose' : IDL.Float64,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Nat,
    'author' : IDL.Text,
    'lastUpdatedAt' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const GlossaryDiagnostic = IDL.Record({
    'key' : IDL.Text,
    'term' : IDL.Text,
  });
  const GlossaryStats = IDL.Record({
    'lastSnapshotVersion' : IDL.Opt(IDL.Nat),
    'currentTermCount' : IDL.Nat,
    'lastBackupTimestamp' : IDL.Opt(IDL.Int),
    'lastRestoreTimestamp' : IDL.Opt(IDL.Int),
  });
  const MarketHour = IDL.Record({
    'closeMinute' : IDL.Nat,
    'closeHour' : IDL.Nat,
    'weekday' : IDL.Nat,
    'openMinute' : IDL.Nat,
    'openHour' : IDL.Nat,
  });
  const Stock = IDL.Record({
    'ltp' : IDL.Float64,
    'dayClose' : IDL.Float64,
    'companyName' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const ResearchPaper = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
  });
  const GlossaryBatchTerm = IDL.Record({
    'key' : IDL.Text,
    'term' : GlossaryTerm,
  });
  const GlossaryBatch = IDL.Record({ 'terms' : IDL.Vec(GlossaryBatchTerm) });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addBlog' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addGlossaryTerm' : IDL.Func([IDL.Text, GlossaryTerm], [], []),
    'addLearningSection' : IDL.Func([IDL.Text, LearningSection], [], []),
    'addResearchPaper' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chatAsk' : IDL.Func([IDL.Text], [ChatAskResponsePayload], ['query']),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteBlog' : IDL.Func([IDL.Nat], [], []),
    'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
    'deleteGlossaryTerm' : IDL.Func([IDL.Text], [], []),
    'deleteLearningSection' : IDL.Func([IDL.Text], [], []),
    'deleteResearchPaper' : IDL.Func([IDL.Nat], [], []),
    'exportGlossarySnapshot' : IDL.Func([], [GlossarySnapshot], []),
    'getAllFeedback' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Feedback))],
        ['query'],
      ),
    'getAllNifty50Data' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Nifty50StockData))],
        ['query'],
      ),
    'getApplicationPaths' : IDL.Func([], [IDL.Text], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogs' : IDL.Func([IDL.Bool], [IDL.Vec(BlogPost)], ['query']),
    'getBlogsByCategory' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlossaryDiagnosticsByPrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GlossaryDiagnostic)],
        ['query'],
      ),
    'getGlossarySnapshotStats' : IDL.Func([], [GlossaryStats], ['query']),
    'getGlossaryTerms' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, GlossaryTerm))],
        ['query'],
      ),
    'getLearningSection' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LearningSection)],
        ['query'],
      ),
    'getLearningSections' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, LearningSection))],
        ['query'],
      ),
    'getMaintenanceStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getMarketHours' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MarketHour))],
        ['query'],
      ),
    'getMarketStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getNifty50Data' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Nifty50StockData)],
        ['query'],
      ),
    'getNifty50Stocks' : IDL.Func([], [IDL.Vec(Stock)], ['query']),
    'getNifty50Symbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getResearchPaper' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ResearchPaper)],
        ['query'],
      ),
    'getResearchPapers' : IDL.Func([], [IDL.Vec(ResearchPaper)], ['query']),
    'getStock' : IDL.Func([IDL.Text], [IDL.Opt(Stock)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeMarketHours' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMarketOpen' : IDL.Func([], [IDL.Bool], ['query']),
    'publishGlossaryBatch' : IDL.Func([GlossaryBatch], [], []),
    'replaceGlossaryWithSnapshot' : IDL.Func([GlossarySnapshot], [], []),
    'restoreGlossaryFromSnapshot' : IDL.Func([GlossarySnapshot], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchGlossary' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, GlossaryTerm))],
        ['query'],
      ),
    'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'submitJobTitle' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArticle' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateBlog' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateBlogUpdatedTime' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateGlossaryTerm' : IDL.Func([IDL.Text, GlossaryTerm], [], []),
    'updateLearningSection' : IDL.Func([IDL.Text, LearningSection], [], []),
    'updateNifty50Data' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateStock' : IDL.Func([IDL.Text, Stock], [], []),
  });
};

export const init = ({ IDL }) => { return []; };