/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'category' : string,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'author' : string,
  'lastUpdatedAt' : bigint,
  'category' : string,
}
export interface ChatAskResponsePayload {
  'sources' : Array<ChatAskResponseSource>,
}
export interface ChatAskResponseSource {
  'id' : [] | [bigint],
  'title' : string,
  'content' : string,
  'type' : ChatSourceType,
  'internetSource' : [] | [InternetResultSource],
}
export type ChatSourceType = { 'internetResult' : null } |
  { 'article' : null } |
  { 'learningSection' : null } |
  { 'glossary' : null };
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface GlossaryBatch { 'terms' : Array<GlossaryBatchTerm> }
export interface GlossaryBatchTerm { 'key' : string, 'term' : GlossaryTerm }
export interface GlossaryDiagnostic { 'key' : string, 'term' : string }
export interface GlossarySnapshot {
  'terms' : Array<[string, GlossaryTerm]>,
  'termCount' : bigint,
  'createdAt' : bigint,
  'version' : bigint,
}
export interface GlossaryStats {
  'lastSnapshotVersion' : [] | [bigint],
  'currentTermCount' : bigint,
  'lastBackupTimestamp' : [] | [bigint],
  'lastRestoreTimestamp' : [] | [bigint],
}
export interface GlossaryTerm {
  'term' : string,
  'example' : string,
  'usage' : string,
  'definition' : string,
}
export interface InternetResultSource {
  'url' : string,
  'title' : string,
  'snippet' : string,
}
export interface LearningSection { 'title' : string, 'content' : string }
export interface MarketHour {
  'closeMinute' : bigint,
  'closeHour' : bigint,
  'weekday' : bigint,
  'openMinute' : bigint,
  'openHour' : bigint,
}
export interface PersistentGlossaryEntry {
  'key' : string,
  'term' : GlossaryTerm,
  'approved' : boolean,
}
export interface ResearchPaper {
  'id' : bigint,
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
}
export interface Stock {
  'ltp' : number,
  'dayClose' : number,
  'companyName' : string,
  'symbol' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArticle' : ActorMethod<[string, string, string], bigint>,
  'addBlog' : ActorMethod<
    [string, string, string, Array<string>, string, bigint, boolean],
    bigint
  >,
  'addGlossaryTerm' : ActorMethod<[string, GlossaryTerm], undefined>,
  'addLearningSection' : ActorMethod<[string, LearningSection], undefined>,
  'addPersistentGlossaryEntries' : ActorMethod<
    [Array<PersistentGlossaryEntry>],
    undefined
  >,
  'addResearchPaper' : ActorMethod<[string, string, ExternalBlob], bigint>,
  'approveAllPersistentGlossaryEntries' : ActorMethod<[], undefined>,
  'approvePersistentGlossaryEntry' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chatAsk' : ActorMethod<[string], ChatAskResponsePayload>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteBlog' : ActorMethod<[bigint], undefined>,
  'deleteFeedback' : ActorMethod<[bigint], undefined>,
  'deleteGlossaryTerm' : ActorMethod<[string], undefined>,
  'deleteLearningSection' : ActorMethod<[string], undefined>,
  'deleteResearchPaper' : ActorMethod<[bigint], undefined>,
  'exportGlossarySnapshot' : ActorMethod<[], GlossarySnapshot>,
  'getAllFeedback' : ActorMethod<[], Array<[bigint, Feedback]>>,
  'getApplicationPaths' : ActorMethod<[], string>,
  'getArticle' : ActorMethod<[bigint], [] | [Article]>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getArticlesByCategory' : ActorMethod<[string], Array<Article>>,
  'getBlog' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogs' : ActorMethod<[boolean], Array<BlogPost>>,
  'getBlogsByCategory' : ActorMethod<[string, boolean], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlossaryDiagnosticsByPrefix' : ActorMethod<
    [string],
    Array<GlossaryDiagnostic>
  >,
  'getGlossarySnapshotStats' : ActorMethod<[], GlossaryStats>,
  'getGlossaryTerms' : ActorMethod<[], Array<[string, GlossaryTerm]>>,
  'getLearningSection' : ActorMethod<[string], [] | [LearningSection]>,
  'getLearningSections' : ActorMethod<[], Array<[string, LearningSection]>>,
  'getMaintenanceStatus' : ActorMethod<[], boolean>,
  'getMarketHours' : ActorMethod<[], Array<[bigint, MarketHour]>>,
  'getMarketStatus' : ActorMethod<[], boolean>,
  'getNifty50Stocks' : ActorMethod<[], Array<Stock>>,
  'getNifty50Symbols' : ActorMethod<[], Array<string>>,
  'getResearchPaper' : ActorMethod<[bigint], [] | [ResearchPaper]>,
  'getResearchPapers' : ActorMethod<[], Array<ResearchPaper>>,
  'getStock' : ActorMethod<[string], [] | [Stock]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeMarketHours' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMarketOpen' : ActorMethod<[], boolean>,
  'publishGlossaryBatch' : ActorMethod<[GlossaryBatch], undefined>,
  'replaceGlossaryWithSnapshot' : ActorMethod<[GlossarySnapshot], undefined>,
  'restoreGlossaryFromSnapshot' : ActorMethod<[GlossarySnapshot], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchGlossary' : ActorMethod<[string], Array<[string, GlossaryTerm]>>,
  'setMaintenanceMode' : ActorMethod<[boolean], undefined>,
  'submitFeedback' : ActorMethod<[string, string, string], bigint>,
  'submitJobTitle' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArticle' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateBlog' : ActorMethod<
    [bigint, string, string, string, Array<string>, string, bigint, boolean],
    undefined
  >,
  'updateBlogUpdatedTime' : ActorMethod<[bigint, bigint], undefined>,
  'updateGlossaryTerm' : ActorMethod<[string, GlossaryTerm], undefined>,
  'updateLearningSection' : ActorMethod<[string, LearningSection], undefined>,
  'updateNifty50Data' : ActorMethod<[string, number, number], undefined>,
  'updateStock' : ActorMethod<[string, Stock], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];