/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GlossaryBatchTerm {
    key: string;
    term: GlossaryTerm;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface GlossaryDiagnostic {
    key: string;
    term: string;
}
export interface GlossaryStats {
    lastSnapshotVersion?: bigint;
    currentTermCount: bigint;
    lastBackupTimestamp?: bigint;
    lastRestoreTimestamp?: bigint;
}
export interface Feedback {
    name: string;
    email: string;
    message: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MarketHour {
    closeMinute: bigint;
    closeHour: bigint;
    weekday: bigint;
    openMinute: bigint;
    openHour: bigint;
}
export interface GlossarySnapshot {
    terms: Array<[string, GlossaryTerm]>;
    termCount: bigint;
    createdAt: bigint;
    version: bigint;
}
export interface PersistentGlossaryEntry {
    key: string;
    term: GlossaryTerm;
    approved: boolean;
}
export interface ResearchPaper {
    id: bigint;
    title: string;
    file: ExternalBlob;
    description: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Stock {
    ltp: number;
    dayClose: number;
    companyName: string;
    symbol: string;
}
export interface ChatAskResponseSource {
    id?: bigint;
    title: string;
    content: string;
    type: ChatSourceType;
    internetSource?: InternetResultSource;
}
export interface Article {
    id: bigint;
    title: string;
    content: string;
    category: string;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    isPublished: boolean;
    tags: Array<string>;
    publishedAt: bigint;
    author: string;
    lastUpdatedAt: bigint;
    category: string;
}
export interface GlossaryTerm {
    term: string;
    example: string;
    usage: string;
    definition: string;
}
export interface GlossaryBatch {
    terms: Array<GlossaryBatchTerm>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LearningSection {
    title: string;
    content: string;
}
export interface ChatAskResponsePayload {
    sources: Array<ChatAskResponseSource>;
}
export interface InternetResultSource {
    url: string;
    title: string;
    snippet: string;
}
export interface Nifty50StockData {
    ltp: number;
    dayClose: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum ChatSourceType {
    internetResult = "internetResult",
    article = "article",
    learningSection = "learningSection",
    glossary = "glossary"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addArticle(title: string, content: string, category: string): Promise<bigint>;
    addBlog(title: string, content: string, author: string, tags: Array<string>, category: string, publishedAt: bigint, isPublished: boolean): Promise<bigint>;
    addGlossaryTerm(key: string, term: GlossaryTerm): Promise<void>;
    addLearningSection(key: string, section: LearningSection): Promise<void>;
    addPersistentGlossaryEntries(entries: Array<PersistentGlossaryEntry>): Promise<void>;
    addResearchPaper(title: string, description: string, file: ExternalBlob): Promise<bigint>;
    approveAllPersistentGlossaryEntries(): Promise<void>;
    approvePersistentGlossaryEntry(key: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chatAsk(_question: string): Promise<ChatAskResponsePayload>;
    deleteArticle(id: bigint): Promise<void>;
    deleteBlog(id: bigint): Promise<void>;
    deleteFeedback(id: bigint): Promise<void>;
    deleteGlossaryTerm(key: string): Promise<void>;
    deleteLearningSection(key: string): Promise<void>;
    deleteResearchPaper(id: bigint): Promise<void>;
    exportGlossarySnapshot(): Promise<GlossarySnapshot>;
    getAllFeedback(): Promise<Array<[bigint, Feedback]>>;
    getAllNifty50Data(): Promise<Array<[string, Nifty50StockData]>>;
    getApplicationPaths(): Promise<string>;
    getArticle(id: bigint): Promise<Article | null>;
    getArticles(): Promise<Array<Article>>;
    getArticlesByCategory(category: string): Promise<Array<Article>>;
    getBlog(id: bigint): Promise<BlogPost | null>;
    getBlogs(includeUnpublished: boolean): Promise<Array<BlogPost>>;
    getBlogsByCategory(category: string, includeUnpublished: boolean): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGlossaryDiagnosticsByPrefix(prefix: string): Promise<Array<GlossaryDiagnostic>>;
    getGlossarySnapshotStats(): Promise<GlossaryStats>;
    getGlossaryTerms(): Promise<Array<[string, GlossaryTerm]>>;
    getLearningSection(key: string): Promise<LearningSection | null>;
    getLearningSections(): Promise<Array<[string, LearningSection]>>;
    getMaintenanceStatus(): Promise<boolean>;
    getMarketHours(): Promise<Array<[bigint, MarketHour]>>;
    getMarketStatus(): Promise<boolean>;
    getNifty50Data(symbol: string): Promise<Nifty50StockData | null>;
    getNifty50Stocks(): Promise<Array<Stock>>;
    getNifty50Symbols(): Promise<Array<string>>;
    getResearchPaper(id: bigint): Promise<ResearchPaper | null>;
    getResearchPapers(): Promise<Array<ResearchPaper>>;
    getStock(symbol: string): Promise<Stock | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeMarketHours(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isMarketOpen(): Promise<boolean>;
    publishGlossaryBatch(batch: GlossaryBatch): Promise<void>;
    replaceGlossaryWithSnapshot(snapshot: GlossarySnapshot): Promise<void>;
    restoreGlossaryFromSnapshot(snapshot: GlossarySnapshot): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchGlossary(searchTerm: string): Promise<Array<[string, GlossaryTerm]>>;
    setMaintenanceMode(enabled: boolean): Promise<void>;
    submitFeedback(name: string, email: string, message: string): Promise<bigint>;
    submitJobTitle(_jobTitle: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateArticle(id: bigint, title: string, content: string, category: string): Promise<void>;
    updateBlog(id: bigint, title: string, content: string, author: string, tags: Array<string>, category: string, publishedAt: bigint, isPublished: boolean): Promise<void>;
    updateBlogUpdatedTime(id: bigint, forcePublishedAt: bigint): Promise<void>;
    updateGlossaryTerm(key: string, term: GlossaryTerm): Promise<void>;
    updateLearningSection(key: string, section: LearningSection): Promise<void>;
    updateNifty50Data(symbol: string, ltp: number, dayClose: number): Promise<void>;
    updateStock(symbol: string, stock: Stock): Promise<void>;
}
import type { Article as _Article, BlogPost as _BlogPost, ChatAskResponsePayload as _ChatAskResponsePayload, ChatAskResponseSource as _ChatAskResponseSource, ChatSourceType as _ChatSourceType, ExternalBlob as _ExternalBlob, GlossaryStats as _GlossaryStats, InternetResultSource as _InternetResultSource, LearningSection as _LearningSection, Nifty50StockData as _Nifty50StockData, ResearchPaper as _ResearchPaper, Stock as _Stock, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addArticle(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addArticle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArticle(arg0, arg1, arg2);
            return result;
        }
    }
    async addBlog(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: bigint, arg6: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlog(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlog(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addGlossaryTerm(arg0: string, arg1: GlossaryTerm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGlossaryTerm(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGlossaryTerm(arg0, arg1);
            return result;
        }
    }
    async addLearningSection(arg0: string, arg1: LearningSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLearningSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLearningSection(arg0, arg1);
            return result;
        }
    }
    async addPersistentGlossaryEntries(arg0: Array<PersistentGlossaryEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPersistentGlossaryEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPersistentGlossaryEntries(arg0);
            return result;
        }
    }
    async addResearchPaper(arg0: string, arg1: string, arg2: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResearchPaper(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResearchPaper(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async approveAllPersistentGlossaryEntries(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAllPersistentGlossaryEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAllPersistentGlossaryEntries();
            return result;
        }
    }
    async approvePersistentGlossaryEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePersistentGlossaryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePersistentGlossaryEntry(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chatAsk(arg0: string): Promise<ChatAskResponsePayload> {
        if (this.processError) {
            try {
                const result = await this.actor.chatAsk(arg0);
                return from_candid_ChatAskResponsePayload_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatAsk(arg0);
            return from_candid_ChatAskResponsePayload_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteBlog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlog(arg0);
            return result;
        }
    }
    async deleteFeedback(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedback(arg0);
            return result;
        }
    }
    async deleteGlossaryTerm(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGlossaryTerm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGlossaryTerm(arg0);
            return result;
        }
    }
    async deleteLearningSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLearningSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLearningSection(arg0);
            return result;
        }
    }
    async deleteResearchPaper(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResearchPaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResearchPaper(arg0);
            return result;
        }
    }
    async exportGlossarySnapshot(): Promise<GlossarySnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.exportGlossarySnapshot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportGlossarySnapshot();
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<[bigint, Feedback]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAllNifty50Data(): Promise<Array<[string, Nifty50StockData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNifty50Data();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNifty50Data();
            return result;
        }
    }
    async getApplicationPaths(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationPaths();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationPaths();
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return result;
        }
    }
    async getArticlesByCategory(arg0: string): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByCategory(arg0);
            return result;
        }
    }
    async getBlog(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlog(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlog(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogs(arg0: boolean): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogs(arg0);
            return result;
        }
    }
    async getBlogsByCategory(arg0: string, arg1: boolean): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogsByCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogsByCategory(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlossaryDiagnosticsByPrefix(arg0: string): Promise<Array<GlossaryDiagnostic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlossaryDiagnosticsByPrefix(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlossaryDiagnosticsByPrefix(arg0);
            return result;
        }
    }
    async getGlossarySnapshotStats(): Promise<GlossaryStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlossarySnapshotStats();
                return from_candid_GlossaryStats_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlossarySnapshotStats();
            return from_candid_GlossaryStats_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlossaryTerms(): Promise<Array<[string, GlossaryTerm]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlossaryTerms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlossaryTerms();
            return result;
        }
    }
    async getLearningSection(arg0: string): Promise<LearningSection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningSection(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningSection(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLearningSections(): Promise<Array<[string, LearningSection]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningSections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningSections();
            return result;
        }
    }
    async getMaintenanceStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceStatus();
            return result;
        }
    }
    async getMarketHours(): Promise<Array<[bigint, MarketHour]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketHours();
            return result;
        }
    }
    async getMarketStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketStatus();
            return result;
        }
    }
    async getNifty50Data(arg0: string): Promise<Nifty50StockData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNifty50Data(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNifty50Data(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNifty50Stocks(): Promise<Array<Stock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNifty50Stocks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNifty50Stocks();
            return result;
        }
    }
    async getNifty50Symbols(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNifty50Symbols();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNifty50Symbols();
            return result;
        }
    }
    async getResearchPaper(arg0: bigint): Promise<ResearchPaper | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchPaper(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchPaper(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearchPapers(): Promise<Array<ResearchPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchPapers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchPapers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStock(arg0: string): Promise<Stock | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStock(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStock(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeMarketHours(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMarketHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMarketHours();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isMarketOpen(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMarketOpen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMarketOpen();
            return result;
        }
    }
    async publishGlossaryBatch(arg0: GlossaryBatch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishGlossaryBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishGlossaryBatch(arg0);
            return result;
        }
    }
    async replaceGlossaryWithSnapshot(arg0: GlossarySnapshot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceGlossaryWithSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceGlossaryWithSnapshot(arg0);
            return result;
        }
    }
    async restoreGlossaryFromSnapshot(arg0: GlossarySnapshot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreGlossaryFromSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreGlossaryFromSnapshot(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchGlossary(arg0: string): Promise<Array<[string, GlossaryTerm]>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGlossary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGlossary(arg0);
            return result;
        }
    }
    async setMaintenanceMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMaintenanceMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMaintenanceMode(arg0);
            return result;
        }
    }
    async submitFeedback(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async submitJobTitle(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitJobTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitJobTitle(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateArticle(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBlog(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: string, arg6: bigint, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlog(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlog(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateBlogUpdatedTime(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogUpdatedTime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogUpdatedTime(arg0, arg1);
            return result;
        }
    }
    async updateGlossaryTerm(arg0: string, arg1: GlossaryTerm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGlossaryTerm(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGlossaryTerm(arg0, arg1);
            return result;
        }
    }
    async updateLearningSection(arg0: string, arg1: LearningSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLearningSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLearningSection(arg0, arg1);
            return result;
        }
    }
    async updateNifty50Data(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNifty50Data(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNifty50Data(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStock(arg0: string, arg1: Stock): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStock(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChatAskResponsePayload_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatAskResponsePayload): ChatAskResponsePayload {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ChatAskResponseSource_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatAskResponseSource): ChatAskResponseSource {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ChatSourceType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatSourceType): ChatSourceType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GlossaryStats_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlossaryStats): GlossaryStats {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ResearchPaper_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchPaper): Promise<ResearchPaper> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InternetResultSource]): InternetResultSource | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LearningSection]): LearningSection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Nifty50StockData]): Nifty50StockData | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResearchPaper]): Promise<ResearchPaper | null> {
    return value.length === 0 ? null : await from_candid_ResearchPaper_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stock]): Stock | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sources: Array<_ChatAskResponseSource>;
}): {
    sources: Array<ChatAskResponseSource>;
} {
    return {
        sources: from_candid_vec_n13(_uploadFile, _downloadFile, value.sources)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: [] | [bigint];
    title: string;
    content: string;
    type: _ChatSourceType;
    internetSource: [] | [_InternetResultSource];
}): {
    id?: bigint;
    title: string;
    content: string;
    type: ChatSourceType;
    internetSource?: InternetResultSource;
} {
    return {
        id: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.id)),
        title: value.title,
        content: value.content,
        type: from_candid_ChatSourceType_n16(_uploadFile, _downloadFile, value.type),
        internetSource: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.internetSource))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastSnapshotVersion: [] | [bigint];
    currentTermCount: bigint;
    lastBackupTimestamp: [] | [bigint];
    lastRestoreTimestamp: [] | [bigint];
}): {
    lastSnapshotVersion?: bigint;
    currentTermCount: bigint;
    lastBackupTimestamp?: bigint;
    lastRestoreTimestamp?: bigint;
} {
    return {
        lastSnapshotVersion: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastSnapshotVersion)),
        currentTermCount: value.currentTermCount,
        lastBackupTimestamp: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastBackupTimestamp)),
        lastRestoreTimestamp: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastRestoreTimestamp))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    file: _ExternalBlob;
    description: string;
}): Promise<{
    id: bigint;
    title: string;
    file: ExternalBlob;
    description: string;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await from_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.file),
        description: value.description
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internetResult: null;
} | {
    article: null;
} | {
    learningSection: null;
} | {
    glossary: null;
}): ChatSourceType {
    return "internetResult" in value ? ChatSourceType.internetResult : "article" in value ? ChatSourceType.article : "learningSection" in value ? ChatSourceType.learningSection : "glossary" in value ? ChatSourceType.glossary : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatAskResponseSource>): Array<ChatAskResponseSource> {
    return value.map((x)=>from_candid_ChatAskResponseSource_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResearchPaper>): Promise<Array<ResearchPaper>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ResearchPaper_n30(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
